CREATE TABLE SUPERSTORE_RAW (
	ROW_ID INT,
	ORDER_ID TEXT,
	ORDER_DATE DATE,
	SHIP_DATE DATE,
	SHIP_MODE TEXT,
	CUSTOMER_ID TEXT,
	CUSTOMER_NAME TEXT,
	SEGMENT TEXT,
	COUNTRY TEXT,
	CITY TEXT,
	STATE TEXT,
	POSTAL_CODE TEXT,
	REGION TEXT,
	PRODUCT_ID TEXT,
	CATEGORY TEXT,
	SUB_CATEGORY TEXT,
	PRODUCT_NAME TEXT,
	SALES NUMERIC,
	QUANTITY INT,
	DISCOUNT NUMERIC,
	PROFIT NUMERIC
);

SELECT
	*
FROM
	SUPERSTORE_RAW;

SET
	DATESTYLE = 'ISO, MDY';

COPY SUPERSTORE_RAW
FROM
	'C:/Program Files/PostgreSQL/18/CSV Files/Sample_Superstore.csv' DELIMITER ',' CSV HEADER;

SELECT
	COUNT(*)
FROM
	SUPERSTORE_RAW;